env:
  global:
    - secure: "gGMlGQQNam2cZNPGf3j5CsftkQM2QvrIF8vTIvv3R4O5qGvdZ7SCKTxysoh7FC+1paPZlZcdCYd6PiVw6nkHPyny6UJWN/litdubJJS3enSiuHYQxFAB4XM2i+yQDTuTUNkOIPPxBDGbLELmEW5Gjgv7JSNzFviVrYkdzx65HYU="
    - secure: "aWO9nUU6D5ap1vaPwzE9Tt8T6dAB34iXlvn8FnMSKkZ/8ENLambXdeJJbWsDp112hB/VVX/llRmuEm3mV1SCpPJFkHhf/Sos7SvaanxFSGhm8Y/SFVRiKULTj7RhMLQhu6swq7ANJPsGsWkrPQfNS8sUaOZV2yxH4X+uYhnq6no="
before_install:
- sudo apt-get install lftp

script:
    - "lftp -u $FTP_USER,$FTP_PASSWORD -e \"set ftp:ssl-allow no; mirror -R -e plugins/          /web/plugins               ; exit\" ftp://f1.is-leibinger.de/"
    - "lftp -u $FTP_USER,$FTP_PASSWORD -e \"set ftp:ssl-allow no; mirror -R -e themes/           /web/themes                ; exit\" ftp://f1.is-leibinger.de/"

    - "lftp -u $FTP_USER,$FTP_PASSWORD -e \"set ftp:ssl-allow no; mv   /web/app/storage/cache    /web/app/storage/cache_    ; exit\" ftp://f1.is-leibinger.de/"
    - "lftp -u $FTP_USER,$FTP_PASSWORD -e \"set ftp:ssl-allow no; mv   /web/app/storage/twig     /web/app/storage/twig_     ; exit\" ftp://f1.is-leibinger.de/"
    - "lftp -u $FTP_USER,$FTP_PASSWORD -e \"set ftp:ssl-allow no; mv   /web/app/storage/sessions /web/app/storage/sessions_ ; exit\" ftp://f1.is-leibinger.de/"

    - "lftp -u $FTP_USER,$FTP_PASSWORD -e \"set ftp:ssl-allow no; mkdir                          /web/app/storage/cache     ; exit\" ftp://f1.is-leibinger.de/"
    - "lftp -u $FTP_USER,$FTP_PASSWORD -e \"set ftp:ssl-allow no; mkdir                          /web/app/storage/twig      ; exit\" ftp://f1.is-leibinger.de/"
    - "lftp -u $FTP_USER,$FTP_PASSWORD -e \"set ftp:ssl-allow no; mkdir                          /web/app/storage/sessions  ; exit\" ftp://f1.is-leibinger.de/"

    - "lftp -u $FTP_USER,$FTP_PASSWORD -e \"set ftp:ssl-allow no; rm -r                          /web/app/storage/cache_    ; exit\" ftp://f1.is-leibinger.de/"
    - "lftp -u $FTP_USER,$FTP_PASSWORD -e \"set ftp:ssl-allow no; rm -r                          /web/app/storage/twig_     ; exit\" ftp://f1.is-leibinger.de/"
    - "lftp -u $FTP_USER,$FTP_PASSWORD -e \"set ftp:ssl-allow no; rm -r                          /web/app/storage/sessions_ ; exit\" ftp://f1.is-leibinger.de/"

notifications:
  email:
    recipients:
      - mailport@mikescher.de
      - benz.armin89@gmail.com
      - simon.streblow@sam-dev.de
    on_success: always
    on_failure: always

# Fail if files other than themes & plugins have changed